### ISSUE TITLE
Including SQLite.Interop.dll

### ISSUE THREAD

**Issue by NeoID** [Fody/Costura#113]
Has anyone managed to include SQLite.Interop.dll using Fody?
Upon build a x64 and x86 directory is created, but I would love to have everything included in my single exe file.

I've added the two dll files to my project, changed them to embed and copy always, but they are still not used. Anyone done this before with this library?

**Comment by distantcam** [comment]
Win32 does not support loading native libraries into a process from anywhere other than disk. See http://stackoverflow.com/questions/22186997/dynamically-load-native-embedded-dll-from-c-cli-clr-based-project-dll

Costura embeds the libraries into the main exe, then at startup the exe will put the libraries on disk so they can be loaded.

**Comment by NeoID** [comment]
Thanks for the link. I found some useful information resulting in the following fix:

* Make sure the solution is set to "Any CPU" in the build settings
* I've created two subfolders in my project: costura64 and costura32
* Add the following to FodyWeavers.xml:

  <Costura>
    <Unmanaged32Assemblies>
      SQLite.Interop
    </Unmanaged32Assemblies>
    <Unmanaged64Assemblies>
      SQLite.Interop
    </Unmanaged64Assemblies>
  </Costura>

I'm now able to delete both x64 and x86 folders created by Sqlite and still use the application without any dependencies errors! :)

**Comment by NeoID** [comment]
While the above works, I get the following message:

Native library pre-loader failed to get setting "No_PreLoadSQLite" value: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.UnsafeNativeMethods.GetXmlConfigFileName()
   at System.Data.SQLite.UnsafeNativeMethods.GetSettingValue(String name, String default)

**Comment by mikemankus** [comment]
NeoID,

What was your solution to this problem? I am still unable to embed the SQLite Interop.

**Comment by NeoID** [comment]
@mikemankus: Hope this might help:
http://idmedia.no/general/including-sqlite-interop-dll-into-your-c-project/

**Comment by mikemankus** [comment]
Yes, incredibly helpful. Solved the problem - thank you!

**Comment by pjquirk** [comment]
@IDmedia Regarding the `ArgumentNullException`, see [this ticket I opened with System.Data.SQLite](https://system.data.sqlite.org/index.html/tktview/da685c0bacca97c43bde3f00c7f03d3b4ecf1ac5).  It's been fixed and hopefully will be deployed soon.

**Comment by Xan-Kun** [comment]
In my case there was also a
      `sqlite3.dll`
I did the same as with the SQLite.Interop.dll and now it works perfectly (don't forget to set it as "embedded resource"! :-) )

**Comment by 0xced** [comment]
Here's another solution to embed the x86 and x64 versions of `SQLite.Interop.dll` that doesn't involve manually copying anything:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
        <!-- We don't need to copy SQLite.Interop.dll since they are embedded with Costura (used by %USERPROFILE%\.nuget\packages\system.data.sqlite.core\{version}\build\net46\System.Data.SQLite.Core.targets) -->
        <CopySQLiteInteropFiles>false</CopySQLiteInteropFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Costura.Fody" Version="3.3.3" />
        <PackageReference Include="System.Data.SQLite.Core" Version="1.0.111" />
    </ItemGroup>

    <Target Name="EmbedSQLiteInteropFiles" BeforeTargets="ResolveReferences">
        <ItemGroup>
            <!-- Condition on item metadata trick adapted from https://stackoverflow.com/questions/5103026/in-msbuild-can-i-use-the-string-replace-function-on-a-metadata-item/8904902#8904902 -->
            <EmbeddedResource Include="@(SQLiteInteropFiles)">
                <!-- Syntax could be simplified in the future in MSBuild, see [Metadata should support instance methods](https://github.com/microsoft/msbuild/issues/1155) -->
                <Link Condition="$([MSBuild]::ValueOrDefault('%(Identity)', '').Contains('x86'))">costura32\%(Filename)%(Extension)</Link>
                <Link Condition="$([MSBuild]::ValueOrDefault('%(Identity)', '').Contains('x64'))">costura64\%(Filename)%(Extension)</Link>
            </EmbeddedResource>
        </ItemGroup>
    </Target>

</Project>
```

Here's how it works:

* Setting `CopySQLiteInteropFiles` to `false` prevents the x86 and x64 directories being copied in your output directory. We don't need them copied since they will be embedded by Costura.

* The `System.Data.SQLite.Core` NuGet package has a *.targets file that define the `SQLiteInteropFiles` item group. We use this item group for defining the `EmbeddedResource` item group. Then with some MSBuild magic, we embed `SQLite.Interop.dll` in both `costura32` and `costura64` directories.

**Comment by ice0030** [comment]
I use costura to embed sevenzipsharp find 2 problems
i use the following config
 <Costura >
    <Unmanaged32Assemblies>
      7z
      SQLite.Interop
    </Unmanaged32Assemblies>
    <Unmanaged64Assemblies>
      7z
      SQLite.Interop
    </Unmanaged64Assemblies>
  </Costura>
it did work ,
SevenZipSharp.dll  7z.dll(x86) 7z.dll(x64) did embeded in
but SevenZipSharp call interface need to set 7z dll path like
SevenZip.SevenZipExtractor.SetLibraryPath(@"./7z.dll");

problem1:SevenZipSharp.dll must physically exist in the same dir with exe,if not,exception like this:
:“SevenZip.SevenZipLibraryManager”的类型初始值设定项引发异常

problem2:even if SevenZipSharp.dll physically exist in the same dir with exe, exception like this:
Can not load 7-zip library or internal COM error! Message: can not change the library path because the file "./7z.dll" does not exist.(how should i write the path string)

although costura did embed in all the dll,but not work,why?

**Comment by ice0030** [comment]
` <Costura >
    <Unmanaged32Assemblies>
      7z
      SQLite.Interop
    </Unmanaged32Assemblies>
    <Unmanaged64Assemblies>
      7z
      SQLite.Interop
    </Unmanaged64Assemblies>
  </Costura>`

**Comment by GeertvanHorrik** [comment]
Please don't revive topics, create a new one. I will lock this thread.
