### ISSUE TITLE
[v2] Allow Costura to be used with libraries

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Costura#146]
On a library, I get this:

"1>MSBUILD : error : Fody: Costura only works with executables."

Although I am aware of the complications, I would love Costura not to prevent me from using this in libraries. It's working fine for us in libraries (sometimes we need to hide away some dependencies).

**Comment by distantcam** [comment]
Sorry, Costura was never meant to support libraries. Instead I would recommend ILMerging your libraries together.

**Comment by SimonCropp** [comment]
@GeertvanHorrik ping me if u want to have a call about it?

**Comment by GeertvanHorrik** [comment]
@SimonCropp ping

**Comment by SimonCropp** [comment]
@GeertvanHorrik simon.cropp on skype

**Comment by akamyshanov** [comment]
Hi everyone. First of all, thanks for the wonderful tool.

I fully agree with @GeertvanHorrik. I see no reasons why to strictly forbid Costura usage with assemblies  with code like this:

https://github.com/Fody/Costura/blob/52630a7341e1a8193c0c208a1b9dd98d2096699c/src/Costura/ModuleWeaver.cs#L25
```C#
if (ModuleDefinition.EntryPoint == null)
{
  throw new WeavingException("Costura only works with executables.");
}
```

Costura has been working quite good with assemblies for a long time and I would like to continue using the latest versions, even if it warns me "use with assemblies at your own risk". Maybe it's better to produce a warning in the log instead of an error?

**Comment by bellekci** [comment]
It was working just fine. Why did you prevent it? Please revert this error.

**Comment by distantcam** [comment]
@bellekci It was not working just fine. Please fix the following issues and I'll reconsider.

https://github.com/Fody/Costura/issues/104
https://github.com/Fody/Costura/issues/125
https://github.com/Fody/Costura/issues/144

**Comment by akamyshanov** [comment]
Hello @distantcam
- #104 @GeertvanHorrik suggested a solution. Can't add anything to this though, haven't experienced this issue.
- #125 A totally invalid issue without any repro. Most probably unrelated with Costura at all.
- #144 How is this Costura's fault? This is just an incompatibility that has a workaround.

I understand your point of view, but there is a various number of use cases out there. For example, we are loading an assembly with Costura on board in a separate `AppDomain` from a byte array via native CLR hosting. This way nothing gets loaded into the default domain, thus Costura doesn't run there. This way everything works absolutely fine and I can't think of anything that's very different from an executable in this case.

IMHO. Forbidding usage with DLLs (when it DOES work) is very unreasonable in my opinion.
Suggestions:
- Showing a warning
- Forcing users explicitly allow usage with DLLs (so that they know what they're dealing with)

Thanks in advance.

**Comment by distantcam** [comment]
@akamyshanov Those are just the public issues I know about. There's other scenarios that I have no idea about, like what if 2 libraries both use Costura and try to load into the same appdomain a common library like Json.net? When the user comes to me with that problem how do I solve that? Another problem is static code can run from a library before the Costura code that hooks the assembly loader.

> I understand your point of view, but there is a various number of use cases out there. For example, we are loading an assembly with Costura on board in a separate AppDomain from a byte array via native CLR hosting. This way nothing gets loaded into the default domain, thus Costura doesn't run there. This way everything works absolutely fine and I can't think of anything that's very different from an executable in this case.

Yeah, Costura was designed for creating a single exe easily without having to worry about app domains and all that stuff. If you understand that stuff then I kinda feel you have enough knowledge to fork this project and support libraries yourself. There's nothing complex about how Costura is built.

**Comment by akamyshanov** [comment]
@distantcam
> When the user comes to me with that problem how do I solve that?

You close the issue 😄. Because the user explicitly agreed to deal with library-related stuff himself and was aware of the dragons ahead. E.g.
```XML
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
	<Costura AwareOfLibraryRelatedProblemsAndWillNotPostIssuesOnGithub="true"/>
</Weavers>
```
There are even issues like [these](https://github.com/Fody/Costura/issues/167) but I hope they don't bother you too much 😉.

> fork this project and support libraries yourself

Sure, that's an option. But it'll make me sad to do that and to set up NuGet packages because of a single line of code.

**Comment by distantcam** [comment]
@akamyshanov 

> You close the issue :smile:.

I did that. People are still commenting on the issue. Now I'm going to lock it. :smile:
