### ISSUE TITLE
Costura unable to load assembly when CLR is hostet from a not .net application

### ISSUE THREAD

**Issue by dprochownik** [Fody/Costura#170]
Hi,
Costura works for me more than fine as long as merged assemblies are used from an applications written in C#. Unfortunately when I've tried to use it in the project which is not written in .Net but starts that framework manually I got error: 
`Could not load file or assembly 'BlaBlaBla, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`

Currently I'm using TJclClrHost component from JclDotNet library to load C# assemblies from an old Delphi projects, which I want to partially migrate to the C#.

**Comment by distantcam** [comment]
@akamyshanov Any ideas? This is another situation that Costura was not designed for and is effectively a library situation.

**Comment by dprochownik** [comment]
I'm sure it wasn't designed for that, but at the moment I can't see any reason why it doesn't work. 
In both cases (C# app and .Net started manually) resolving assembly references is on the .Net framework side, which renders that error.

**Comment by distantcam** [comment]
Costura uses a hack in the managed framework for running a "module initializer". Module initializers were created to allow C++/CLI code to run some initialization code as part of their setup. It was meant for compiler use only and not for user code. Because it's a hidden feature it doesn't always run and when it doesn't that's when Costura fails.

.NET executables are about the only time I know of that is guaranteed to run the module initializer. Also Costura was designed so that you could distribute an exe as a single file.

**Comment by akamyshanov** [comment]
@dprochownik can you narrow it down to a sample project?
Not much of a Delphi expert (haven't written a single line of code), but with [C++ CLR Hosting](https://code.msdn.microsoft.com/windowsdesktop/CppHostCLR-e6581ee0) Costura works absolutely fine:
0. Init CLR
1. Create `AppDomain` (DefaultDomain also works fine)
2. Load Costura-processed assembly from file or byte array
3. Call some static methods

Obviously, as @distantcam mentioned, the module initializer doesn't get called, so Costura is not initialized either.
You can try using [this](https://github.com/fody/moduleinit) to check whether the module initializer gets called or not in your scenario.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
