### ISSUE TITLE
ClickOnce problems

### ISSUE THREAD

**Issue by tripleacoder** [Fody/Costura#220]
Does Costura work with ClickOnce? 

I have made a library that I want to package 32 bit and 64 bit dll's with as resources and then compile the library in the AnyCPU configuration.
I can build the project with AnyCPU and run it in the debugger, but when I publish with ClickOnce it seems to deploy the embedded dll's also. The files are getting extracted from the resources somehow... then when the program runs it finds that the dll's with the wrong bitness are present in the folder so I get the BadImageFormat exception.

**Comment by tripleacoder** [comment]
When I leave out the dlls, ClickOnce gives me an error when I try to install:

![image](https://user-images.githubusercontent.com/29861785/27792143-9fce1b1c-5ff8-11e7-9465-de1c489995f4.png)

**Comment by tripleacoder** [comment]
It seems to work now. I had to go in under Publish->Application Files and mark all the dlls as Excluded.

**Comment by distantcam** [comment]
Just out of curiosity, why use Costura with ClickOnce?

**Comment by tripleacoder** [comment]
This is for an enterprise deployment, we try to use ClickOnce where possible.

**Comment by distantcam** [comment]
That doesn't explain why you use Costura. Costura is designed for apps that are distributed as a single exe, but ClickOnce copies and installs all the files (exe and dll) so Costura isn't needed.

**Comment by tripleacoder** [comment]
Costura also has logic to select the correct dll at runtime. Originally I tried to develop it myself, but couldn't get it to work. So I decided to try Costura.

**Comment by Lakritzator** [comment]
I am actually using the same thing, and it's a bit contra productive... The question "why" is not so far fetched, but there are reasons... in my case, I also have a non click-once "version" and only want to have one artifact.

For me the problem with this setup, is not directly Costura or ClickOnce. The problem is that updating a NuGet package removes the package and installs it again. This causes an update in the Application-Files (it's like installing a new package) so I need to modify this after every NuGet package update.

Not a good solution for automating a build!

**Comment by SimonCropp** [comment]
sorry but @distantcam is correct your scenario is not something costura is attempting to address
