### ISSUE TITLE
Ignore existing DLL-files on disk (load only embedded DLLs)

### ISSUE THREAD

**Issue by DevNotNull** [Fody/Costura#334]
#### Is the feature request related to a problem

I have several different exe-files with DLLs in the same directory. If i embed a DLL with costura in the exe, an existing DLL on disk will be preferably loaded (also if it is an older version of that DLL) ignoring the embedded DLL.

#### Describe the solution

I would like to have an option, that completly ignores existing DLL-files on disk and only looks for the embedded DLLs in the exe-file to avoid conflicts.

If that is not (easily) possible i would appreciate a possible workaroud to the described behaviour.

Thanks in advance.

**Comment by tom-englert** [comment]
There is no code in Costura trying to load an assembly from disk before loading the embedded assembly.
Maybe these assemblies are loaded beforehand by some other means?

**Comment by DevNotNull** [comment]
I thought the line 39 in ILTemplate.cs does exactly this:
`var assembly = Common.ReadExistingAssembly(requestedAssemblyName);`
...and only if this is not found its loaded from the embeded resource in line 47:
`assembly = Common.ReadFromEmbeddedResources(assemblyNames, symbolNames, requestedAssemblyName);`
Please correct me if i am wrong! Otherwise it could be something .net-builtin (outside of Costura).

**Comment by tom-englert** [comment]
`ReadExistingAssembly` only checks if the assembly is already loaded, but it does not load it.

**Comment by DevNotNull** [comment]
Thanks for clarifying! I really like Costura and use it regularly. Keep up the good work.

**Comment by photchkiss** [comment]
Is it possible to override the behavior outlined above and force the reload of the assembly from embedded resources? I have a situation where the assembly has already been loaded in the app domain, but I have a different version being referenced by another dll. Because the app domain has already loaded the assembly, it doesn't use the embedded resource, but instead uses the first one loaded.

**Comment by SimonCropp** [comment]
@photchkiss currently no. costura is designed to be used on the top level app, ie the exe. in that context "what assemblies on disk" are the responsibility of how the exe is deployed. if you do or dont want something loaded from disk, then do or dont deploy it.

**Comment by photchkiss** [comment]
@SimonCropp Bummer, our use case is within an application where we don't really control the deployment mechanism. We use a third-party loan origination system where you are asked to reference an assembly, but it can only be one. As you switch between different parts of the application, different assemblies are referenced. I was hoping that we'd be able to tell it to reload the embedded resource each time because we don't have a good way within this system to control the execution context. Thanks for the info!

**Comment by SimonCropp** [comment]
@photchkiss i recommend trying https://github.com/dotnet/ILMerge or https://github.com/gluck/il-repack

**Comment by tom-englert** [comment]
Or, to stay within the fody eco-system: https://github.com/tom-englert/ILMerge.Fody
