### ISSUE TITLE
UWP and packages

### ISSUE THREAD

**Issue by wvdvegt** [Fody/Costura#351]
Question: I'm trying to use Costure.Fody on an UWP application that uses packages like Microsoft.Toolkit.Uwp.Notification. 

I can't however get Costura.Fody to inclide tweave the assemblies into the main app (maybe because in the project references I do not get to see individual assemblies nor have the option to set copy to local.

**Comment by SimonCropp** [comment]
given UWP has its own approach to packaging, why would you use costura? ie there would seem to be no benefit in combining assemblies?

**Comment by SimonCropp** [comment]
Also to be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue).

**Comment by GeertvanHorrik** [comment]
AFAIK, there is no need to use Costura on UWP. The reason is *all non-winrt* components are being compiled into native code and result in a single .dll. 

If you look into %programfiles%\WindowsApps and pick any app, you will see only:

1) AppName.exe
2) AppName.dll => contains all the native generated code, including the *used* references / dependencies
3) Win-RT components (if you find a .dll, it's a win-rt component)
4) Directories with resources for the dependencies (which are required, you can't get rid of these)

So I guess Costura is not the way to achieve what you want (but not sure what you want to achieve anyway).

**Comment by wvdvegt** [comment]
It was just the 2nd project I tried (first desktop one went smooth but had only a few assemblies, the UWP gave quite some issues I did not expect but has much more assemblies).

I know it's probably not necessary or a good idea to use it on an UWP app due to it's complexity (and they get packaged anyway). 

What I did not expect was all kind of funky exceptions about missing  .Net frameworks etc.

So my thoughts are to use it carefully like ILMerge as it can ruin your project at runtime, but it seems a very good alternative to ILMerge that seem to have less side-effects.

**Comment by GeertvanHorrik** [comment]
You should always use something like Costura with care (any weaver, actually). For each project, you should ask yourself: do I actually need this?

In case of UWP, there is no use-case (at least I can't think of one), so never use it on UWP apps.

**Comment by GeertvanHorrik** [comment]
Closing this ticket. If you feel it hasn't been answered, let us know. Thanks!
