### ISSUE TITLE
Issue creating temporary assemblies in a Visual Basic forms application

### ISSUE THREAD

**Issue by staht** [Fody/Costura#463]
Visual Basic forms application with embedded unmanaged dll. The dll was created in visual fortran. The application will not extract the embedded resource to the Temp\Costura folder. I did a quick C# forms application and it works fine. I've tried versions of Costura going back to 3.3.2 and up to the current. I've tried it in Visual Studio Professional 2017 and 2019.

**Comment by staht** [comment]
Thank you for the response. I am attaching a repro. 
I am using VS 2019 Pro and Costura 4.1 on Windows 10 v1903 build 18362.418

The attached basic VB.Net forms application has one 32 bit umanaged dll included. Historically, at least in regards to every C# forms application I've done. Costura will unfailingly create the temporary assembly in the "User"\AppData\Local\Temp\Costura folder. 

[CosturaEmbeddedResourceIssue.zip](https://github.com/Fody/Costura/files/3816398/CosturaEmbeddedResourceIssue.zip)

Thank you for your time.

**Comment by SimonCropp** [comment]
@staht 

> Did you read the issue template about being a patron?

**Comment by GeertvanHorrik** [comment]
I *quickly* checked your sample and there are 2 things that I find curious:

* I don't even see the usage of the type or the assembly referenced (I thought Costura kicks in whenever the appdomain requests the type)
* The name of the resource is weird (check it out with .NET Reflector or dotPeek)

Since I don't use VB.NET myself and you are not a patron, I have no incentive to fix this issue myself. I will close this ticket as described in the original issue template.
