### ISSUE TITLE
DLL Merging Malformed

### ISSUE THREAD

**Issue by Al-Imran** [Fody/Costura#505]
My system is
* Visual Studio 2017
* Fody 4.2.1 (Had to downgrade due to MSBuild 16 error)
* Costura 3.3.3 
* Platform: .NET version: 4.6.1

The building process is successful with or without merging. One of the DLLs throws an error when I run the merged executable. My guess is since one of the libraries is inside a folder, merging operation led to the unexpected error. What I mean is:

_ProjectName
-DLL_Folder
--Some.dll
-More.dll
-ProjectName.exe_

I think the _Some.dll_ is causing the issue. Moving this outside the folder is NOT an option. How do I solve this?

**Comment by GeertvanHorrik** [comment]
We don't support older versions, because how would you want to use the fix with the latest costura / fody version if you are using VS 2017?

**Comment by Al-Imran** [comment]
I didn't quite grasp what you said. Since you don't support older versions, my questions would be

1. Is it guaranteed that the latest versions of Costura and Fody will resolve the issue? If yes, I will have to install Visual Studio 2019, which is a time taking process.
2. Is there any workaround for _**Fody is only supported on MSBuild 16 and above. Current version: 15.**_ error in Visual Studio 2017? This was the reason I had to downgrade.
3. Any other solutions?

**Comment by SimonCropp** [comment]
> Is it guaranteed that the latest versions of Costura and Fody will resolve the issue? If yes, I will have to install Visual Studio 2019, which is a time taking process.

It is impossible to tell if your problem is caused by an older VS, and older fody, an older costura, or some edge case in you assembly. so no it is not guaranteed to work on the latests version. but if you can repro the problem on current versions it is more likely to be fixed

> which is a time taking process

last i checked it was less than 15 min to install VS2019

> Is there any workaround for Fody is only supported on MSBuild 16 and above. Current version: 15. error in Visual Studio 2017? This was the reason I had to downgrade.

no there is no work around. this was conscious decision to stop supporting VS2017, since too much effort was being spent by maintainers in this space.

> Any other solutions?

 * you can fork the project.
 * move to using post sharp
 * if you went to the effort of doing  PR that fixes the problem, and that fix targets both master and the old version, it might be possible to do a patch of the old version. but that would depend on the effort involved

**Comment by Al-Imran** [comment]
So, I went for VS2019 and the latest Costura.Fody (v4.1.0). The issue prevails. I still am having problems merging the DLL especially the [PdfiumViewer](https://github.com/pvginkel/PdfiumViewer). The thing is only the merged exe throws the error. Normal build works just fine.

**Comment by GeertvanHorrik** [comment]
Since we don't have this use-case ourselves, and this project is in maintenance mode, we will probably only fix this when someone else creates a PR or the maintainers get paid to build this custom requirement.

If you believe this is a bug of a usual use-case, feel free to create a repro. But I think you want to specify a target directory? In that case you could consider embedding the file as embedded resource yourself and extract it at startup.
