### ISSUE TITLE
costura32/costura64 subfolders 

### ISSUE THREAD

**Issue by stgeorge** [Fody/Costura#85]
Seems like embedded resources in subfolders under costura32/costura64 are not supported (they end up in the same directory as the DLL's when unpacked into temp directory).

I'm trying to embed CefGlue (which in turn needs native DLL's from Chromium Embedded Framework). The structure of these DLLs are:

cef.pak
d3dcompiler_43.dll
d3dcompiler_46.dll
devtools_resources.pak
ffmpegsumo.dll
icudtl.dat
libEGL.dll
libGLESv2.dll
locales/_.pak -> get turned into locales._.pak

So the locales files are not being found. Has anyone embedded CefGlue and CEF successfully?

**Comment by ahmetabdi** [comment]
:+1:

**Comment by bellekci** [comment]
Is this implemented on the 2.0 betaversion?

**Comment by bellekci** [comment]
I have a similar need.
I have a dll which loads a native dll inside a sub-folder. For example:

app-net.dll
native/app-native.dll

Even though I add app-native.dll as embedded resource, app-net.dll cannot find it.
Is there any workaround? Or can you put me in correct direction so that I implement and submit a PR?

**Comment by cipri-tom** [comment]
Same for me. Namely, I am using [`PdfiumViewer`](https://github.com/pvginkel/PdfiumViewer) as a NUGet package which, in turn, depends on native libraries. These were installed, by default, into `x86`/`x64` folders but I moved them to `costura32`/`costura64` and set them as embedded resource.

When I build my solution, the *Output* tab shows the Costura message that `PdfiumViewer.dll` and `PdfiumViewer.resources.dll` were successfully embedded. However, when I'm trying to use my application, I get an exception from `PdfiumViewer.NativeMethods`. This doesn't happen when I don't use `Costura`

This seems similar to the above problem, though not exactly the same because my native dll's don't need to reside in a subfolder. Any ideas ?

**Comment by eladavron** [comment]
Having the same issue with emgu and it's related packages, specifically
`cvextern.dll` and `opencv_ffmpeg310.dll`.
I can't get them to embed no matter what I do.
Any progress / revelations on this?

**Comment by TFenby** [comment]
Same issue as @eladavron. Anyone got a workaround?

**Comment by mossc** [comment]
Same issue as @eladavron. Anyone got a workaround?

**Comment by scamplogic** [comment]
Same issue as @eladavron. Anyone got a workaround?

**Comment by distantcam** [comment]
> Same issue as @eladavron. Anyone got a workaround?

Ok fine, you got us. There is a workaround, but it's top secret. I'll only tell one of you. Check your email.

**Comment by scamplogic** [comment]
*waits on bated breath*

**Comment by mikemoore13** [comment]
any news about the workaround ?

**Comment by distantcam** [comment]
@mikemoore13 You haven't told anyone about it yet.

**Comment by francisrc** [comment]
I have a similar issue. Could someone please share the workaround?

**Comment by SimonCropp** [comment]
@flux88 happy to accept a PR that fixes this

**Comment by flux88** [comment]
Apologies works! I had to set to Embedded Resource and do not copy.

**Comment by IJeffray** [comment]
Still have this issue with specifically and only cvextern.dll .. other DLLs work fine including others from OpenCV such as opencv_videoio_ffmpeg490_64.dll
