### ISSUE TITLE
Ability to optionally include all assemblies in the output directory

### ISSUE THREAD

**Issue by icnocop** [Fody/Costura#92]
Thank you for Costura.Fody.

I'd like to request the ability to optionally include all assemblies in the output directory and not just those included as a project reference.

In this way if there are any new dependencies of a project reference, they will automatically get copied to the project's output directory by msbuild, and then costura can automatically include them as embedded resources.

Thank you.

**Comment by distantcam** [comment]
Unless they're referenced by code, the assembly won't have a reference to the library and there's no need to embed the reference.

If code is using the reference then everything works normally.

I don't see what you're trying to do with this. Could you please explain your scenario?

**Comment by icnocop** [comment]
For example, assembly A references assembly B. Assembly B references assembly C. But if assembly A doesn't reference assembly C, assembly C won't get included as an embedded resource and may cause run-time errors when just deploying assembly A.

Thank you.

**Comment by jorgensigvardsson** [comment]
Only direct references are included, or have I missed anything? I have a scenario where I have to add all references to my main executable, in order to have them embedded into the final executable. Is this a bug? If it is not, I'd like to extend Costura such that it embeds indirect references as well. For this to happen, I need to know how to debug and test Costura. Does anybody have any good advice on how to set up my environment for that?

**Comment by jorgensigvardsson** [comment]
Nevermind. I figured it out. I will submitting a pull request soon.

**Comment by jorgensigvardsson** [comment]
Please see pull request: https://github.com/Fody/Costura/pull/156

**Comment by maurodx** [comment]
I'b like to see the pull request #156 merged. I have the same problem of @icnocop

**Comment by distantcam** [comment]
I created an example that has an indirect reference, and works with the latest version of Costura.

https://github.com/distantcam/SimpleCosturaExample

**Comment by icnocop** [comment]
Thank you.

I think the problem occurs when there's an assembly reference instead of a project reference, like in your sample code, but I would have to test it to make sure.

**Comment by jorgensigvardsson** [comment]
@icnocop yes, that's the problem for me. "Third party" references are sometimes not included. This PR does indeed fix it.

**Comment by distantcam** [comment]
How does it work without Costura then? The 3rd party library has to be copied into the output folder. How is that done?

**Comment by jorgensigvardsson** [comment]
Typically, the compiler copies the dependencies into the output folder. However, when using Costura, you typically don't want loose hanging .dlls - you only want one .exe. If you want Costura (as is), to handle all dependencies, you'd have to add a reference to all dependencies from the main executable. We used to do this manually (well, still are, as we don't want the burden of maintaining a git clone at work), but it got old pretty quickly.

I can't tell you the exact conditions when Costura doesn't pick up all references, because it was too long ago I wrote the PR. All I know that it doesn't pick them all up. I recently got burned by this (we forgot to add references to the main .exe). If memory serves me well, the supplied tests validates the fix (and the opposite). 

The PR will do a depth first search for all referenced assemblies (short circuited on the directory in which the exe is located).

**Comment by jaelys** [comment]
My program references a third-party managed DLL, and third-party must set the path of unmanaged DLLs

I do not know how to use Costura to solve this problem?

1. Can I learn that Costura unpacks the unmanaged dll's path at the very beginning?

Can I specify the default path for unmanaged dll decompression so that I can set the path to a third-party managed dll?

Can you please expert guidance?

Sorry for the google language translation
